### PR TITLE
Edit Post Component

### PR DESCRIPTION
**Pull request by mstenflo**
Edit post component

### CODE REVIEW

**Comment by jrzh0714** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
Give it a bit, jenkins is catching up due to the issues with our Ec2

**Comment by ryanmohler17** [comment]
A new build is queue up for this or, I had to kill the first one as it was frozen

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
jenkins build

**Review by jrzh0714 — APPROVED** [review]

**Pull request merged**
