### PR TITLE
Andrew wolf

### PR DESCRIPTION
**Pull request by wolfman30**
- Login-register has the slow-spinning galaxy background
- The login-register has the changes made by Jorge and Jordan to be able to exchange data with the back-end
- Still some minor styling issues with the tabs that can be fixed

### CODE REVIEW

**Comment by ryanmohler172** [comment]
Can one of the admins verify this patch? 
Run `jenkins approve` to approve this pr for building. Run `jenkins build` to build.
You can also run `jenkins whitelist` to whitelist this user for all future prs.

**Comment by ryanmohler17** [comment]
jenkins whitelist

**Comment by ryanmohler17** [comment]
jenkins build

**Comment by ryanmohler17** [comment]
Sorry about this our ec2 is out of space
jenkins build

**Review by jrzh0714 — APPROVED** [review]

**Pull request merged**
